### ISSUE TITLE
freeze after looting empty large box

### ISSUE THREAD

**Issue by d-m-bailey** [sakkaku-dev/nethack-web#34]
After forcing the lock with a crude dagger, I looted the large box with `b` (take out, then put in).
The box was empty, so nothing to take out.
Attempted to put in 1000 zorkmids and the 3 spellbooks.
After hitting `submit`, the screen froze.
<img width="1434" alt="loot_box" src="https://github.com/sakkaku-dev/nethack-web/assets/8349634/931eb66f-a5d7-42ca-88bd-6cee73ad564d">

**Comment by myin142** [comment]
Might have been fixed by #30, but leave it open for now
