### ISSUE TITLE
Sometimes pet/monsters disappear?

### ISSUE THREAD

**Issue by myin142** [sakkaku-dev/nethack-web#37]
Not sure if just out of view or a bug

**Comment by graves501** [comment]
I think the pet/monsters are just out of view. The dungeons are pretty dark so in some rooms the "viewfield" is even more limited. I think in NetHack 3.7.0 there will be different shades of darkness as far as I can tell.

![image](https://github.com/sakkaku-dev/nethack-web/assets/11211125/bcf50119-83b1-4ca8-a25f-6dc55fb770c8)
