### ISSUE TITLE
freeze with zap menu

### ISSUE THREAD

**Issue by d-m-bailey** [sakkaku-dev/nethack-web#40]
mouse over the left wand icon did not reveal the type, so I attempted to `z`ap  it by bringing up the zap menu with `?`.
<img width="1436" alt="zap_menu" src="https://github.com/sakkaku-dev/nethack-web/assets/8349634/da325586-cdb9-4fcf-9e99-0dc332a425a9">

**Comment by myin142** [comment]
Related to #21, which hasn't been implement yet. I didn't know a usage, but now I do, thanks.

And thanks for all the testing. Has been really helpful :)
