### ISSUE TITLE
Can not start from welcome screen.

### ISSUE THREAD

**Issue by d-m-bailey** [sakkaku-dev/nethack-web#48]
Clicking on `a - Start Game` or `b - Load from backup` highlights the button, but nothing else.

Pressing `a` or `b` also has no effect.

Nothing displays in the dev console.

Reloading the page displays this in the dev console.
```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
```

**Comment by myin142** [comment]
Right now you have to confirm with space or enter like in a menu. Probably have to change this since it's not very intuitive

**Comment by d-m-bailey** [comment]
@myin142 thanks for the response. But `space` and `enter` also have no effect for me.

**Comment by d-m-bailey** [comment]
`space` and `enter` *do not* work after selection by mouse.
`space` or `enter` *do* work after selection by keyboard.
