### ISSUE TITLE
Cannot select items after the 52th item in a container.

### ISSUE THREAD

**Issue by d-m-bailey** [sakkaku-dev/nethack-web#88]
The first 26 items in a container are prefixed with `a-z`.
The next 26 items are prefixed with `A-Z`.
After that `0-9` are used as prefixes, but are not selectable.
Selecting another item after attempting to select `0-9` results in a count for the item.

<img width="395" alt="full_container" src="https://github.com/sakkaku-dev/nethack-web/assets/8349634/7869a3ff-ed7b-4561-8577-a16b24b28d90">

**Comment by myin142** [comment]
Do you know how the other ports are solving this? It's a bit difficult to reproduce..

**Comment by d-m-bailey** [comment]
nethack v3.7 only shows a page at a time and re-letters everything on each page when showing container inventory. 
I think I remember another gui port that didn't show letters for items after the 52nd one. You could only choose those with the mouse (or other menu short cut keys like `.`, `%`, etc.).

**Comment by d-m-bailey** [comment]
It's kind of tedious, but you can renamed individual items of stacks. For example, use a pickaxe to split boulders into rocks, pick up one at a time, give it a unique name, stuff it in a container, repeat.

**Comment by myin142** [comment]
Thanks for the info and tips! I'll see what I can do.

**Comment by d-m-bailey** [comment]
This is also a problem when there are over 52 discoveries and you try to name a class of item using `Cd`.
Items prefixed with numbers are unselectable.
After the 62nd item (`a-zA-Z0-9`) there are 7 items prefixed with punctuation `:;<=>?@` which are selectable.
After that, the prefix repeats `A-Z`, but selecting any of these objects results in a prompt to rename the first object in the list with that prefix instead of the selected object.
