### ISSUE TITLE
Missing save file.

### ISSUE THREAD

**Issue by d-m-bailey** [sakkaku-dev/nethack-web#91]
Trying to restart a saved game brings up the "create a new character prompt".
High scores does not show a deceased character so I'm guessing the save file on the server was lost.

`Cav Dwa Mal? Law Phyban` last on dungeon level 23, I believe.

**Comment by myin142** [comment]
Did you just use the "Start Game" button or did you use the backup load?

**Comment by d-m-bailey** [comment]
I tried the "Start Game", and it asked to create a new character. I cancelled that and checked the backup logs. There was a "Phyban" backup, so I started that, but it was a previous character. I quit that and it's in the highscore file as a quit.

**Comment by myin142** [comment]
Did you use the same player name when starting the game? It should usually always create a backup save for each player name.
But not long ago I fixed a bug with the saves on Chrome. It might be related to that. I would recommend reloading the browser cache just in case. (Ctrl+F5 or Shift+F5 might work). You should see a log in the console like `Running version f36fcb...`. But I will keep my eyes open for any problems with the save files.

**Comment by graves501** [comment]
@d-m-bailey FYI: The save games are not saved on the server, they are stored in the browser:

![image](https://github.com/sakkaku-dev/nethack-web/assets/11211125/ab31883f-f4a9-4d97-b3e0-7a9464778296)

**Comment by d-m-bailey** [comment]
@graves501 Thanks!
@myin142 Lost another character, `Zadek`. Same thing. Started with the previous saved character's name (pre-populated in the prompt) and got `Shall I pick...` Here's the contents of the IndexedDB
<img width="740" alt="timestamp" src="https://github.com/sakkaku-dev/nethack-web/assets/8349634/34d5e8a6-d51b-465f-af09-c86f753cc116">

And the contents of Local Storage
<img width="1108" alt="saves" src="https://github.com/sakkaku-dev/nethack-web/assets/8349634/be2eb313-c8b5-4f9d-8d9f-adba2df025b2">

These correspond to the entries on the backup load screen and may not be the most recent data. `Zadek`'s data appears to be pretty close though.

So maybe what happened with `Phyban` is that I tried to resume, but got the `Shall I pick...` prompt and started a new character, caveman, with the same name. The backup for the previous character, wizard, still exists, so the caveman backup appears not to be implicitly created. 
Using Chrome `115.0.5790.102` on macos `13.2.1`.

**Comment by myin142** [comment]
I tried some fixes, hopefully it helps. But to summarize the expected saving behavior:

- If you use `Shift+S` and save in game
   - you can just start the game, nethack still has the save file (in IndexedDB)
   - a backup should be created
- If it's just closed without save
   - there is no save file in nethack anymore, starting will prompt a new character
   - only the backup can be used to get the last save point

that's how it works for me. But maybe there is a change if you get further in the game.

**Comment by d-m-bailey** [comment]
@myin142 Thanks for the explanation.

For me, `Shift-S` saves but does not overwrite the previous backup file.

Does this happen if the same character name is reused for different characters? Or is the timestamp on the save file the creation time of the character and not the save time?

**Comment by myin142** [comment]
One character name should only have one backup file. It will override existing ones. The timestamp should be the last save time, not the creation time, so it's probably not creating a backup. I just recently changed the logic on which files are saved. (see [here](https://github.com/sakkaku-dev/nethack-web/blob/master/src/helper/save-files.ts#L78))

It basically tries to find the correct save file for the current character name and only creates a backup for it. How are your save files named in IndexedDB and what name did you use? Are there any errors in the logs?

**Comment by d-m-bailey** [comment]
Here's the saved files at the start screen.
<img width="370" alt="save_file" src="https://github.com/sakkaku-dev/nethack-web/assets/8349634/9584c7a2-a0b2-47ea-946c-d6daa9a158e5">

Here's the console error after game save.
<img width="361" alt="save_error" src="https://github.com/sakkaku-dev/nethack-web/assets/8349634/02161975-3849-4d9e-9dc4-0a9dd31b4bb9">

**Comment by myin142** [comment]
I have updated it now to log more information when saving. It seems there is some kind of problem when reading the save file. Could you try it again and post the logs?

Note: the `Uncaught RuntimeError: unreachable` error is normal when the game exists.

**Comment by d-m-bailey** [comment]
<img width="354" alt="nosave" src="https://github.com/sakkaku-dev/nethack-web/assets/8349634/c4f99876-1dd8-42e2-b669-a34cf8f0d73f">

**Comment by myin142** [comment]
Sorry about that. I just recently found the problem and trying to work on a solution.

This problem only happens on Chrome and when the save file reaches a certain size. Then Chrome is unable to load the whole file and throws an error. So in the meantime you could play on Firefox, if you want backup files. It still has not happened to me there.

**Comment by myin142** [comment]
Should be fixed now
