### ISSUE TITLE
Version overlaps Cha

### ISSUE THREAD

**Issue by d-m-bailey** [sakkaku-dev/nethack-web#96]
<img width="393" alt="version overlap" src="https://github.com/sakkaku-dev/nethack-web/assets/8349634/12e98b27-7562-4782-8627-f4f2803979eb">

May just be a problem with smaller screens.

**Comment by myin142** [comment]
Yeah, I have noticed it too. This will be fixed in the next release

**Comment by myin142** [comment]
New version released
