### ISSUE TITLE
#adjust will only allow unused letters

### ISSUE THREAD

**Issue by d-m-bailey** [sakkaku-dev/nethack-web#97]
Attempting to #adjust the letter assigned to an inventory item only allows unused letters. There is no problem with the popup showing just the unassigned letters, but letters not in the displayed list should be also allowed.  

Vanilla nethack allows any letter. If another object is already assigned to the new letter, then the letters are swapped. This is the expected behavior.
<img width="803" alt="adjust" src="https://github.com/sakkaku-dev/nethack-web/assets/8349634/13f84207-fcbf-4259-9301-37bf0b2a09a3">

**Comment by myin142** [comment]
Did you try pressing one of the used letters? For me it still correctly swapping the letters of the two items.

**Comment by d-m-bailey** [comment]
Yes. There is no response for any letter not listed in the popup. The popup remains open.

**Comment by d-m-bailey** [comment]
[0Andy.zip](https://github.com/sakkaku-dev/nethack-web/files/12611101/0Andy.zip)
